export default [
  "Yo mama so dumb she tried to ring Taco Bell.",
  "Yo mama is so dumb, she put her phone in airplane mode and waited at the gate for it to take off.",
  "Yo mama's so stupid, she tried to eat Eminem.",
  "Yo momma is so stupid she ate her food stamps.",
  "Yo momma so dumb, she studied for a urine test.",
  "Yo mama is so stupid that she stole free bread.",
  "Yo momma so dumb, she tried to surf the microwave",
  "Yo mama's so stupid she studies for a blood test.",
  "Yo momma so stupid she got locked in a key store.",
  "Yo momma so stupid she got locked in a motorcycle.",
  "Yo mama so dumb, she plays pool in her bathing suit.",
  "Yo mama's so ignorant, she thinks Google is a person.",
  "Yo momma's so stupid, she steals samples from stores!",
  "Yo mama so dumb, she thought KFC was UFC for chickens.",
  "Yo mama's so stupid, she asks for directions to Wi-Fi.",
  "Yo momma is so dumb she tripped over a cordless phone.",
  "Yo momma is so stupid she tried to climb Mountain Dew.",
  "Yo momma so stupid she thought Bruno Mars was a planet.",
  "Your momma so stupid, she tried to steal a free sample.",
  "Yo momma is so stupid she bought tickets to X-Box Live.",
  "Yo mama so dumb, she sold her car to get gasoline money.",
  "Yo mama so confused, she tried to eat Eminem the rapper.",
  "Yo mama so stupid she brought tea bags to the World Cup.",
  "Yo mama is so stupid she murked herself in a rap battle!",
  "Yo mama's so clueless, she gets lost in a revolving door.",
  "Yo momma so stupid she made a appointment with DR. PEPPER",
  "Yo momma's so dumb she doesn't know which date 9/11 is on.",
  "Yo mama so stupid, she tried to save a fish from drowning.",
  "Yo mama's so unintelligent, she argues with Siri and loses.",
  "Yo mama's so stupid, she thought a quarterback was a refund.",
  "Yo mama's so stupid that she got locked inside a motorcycle.",
  "Yo mamma so stupid she tried to use her MetroCard at Subway.",
  "Yo mama's so brainless, she makes sponges look like geniuses.",
  "Yo mama is so stupid that she put a peephole in a glass door.",
  "Yo mama is so stupid that she thinks Tiger Woods is a forest.",
  "Yo mama is so stupid that she took lessons for a player piano.",
  "Yo mama is so stupid that she thinks socialism means partying!",
  "Yo mama so ridiculous, she thought a quarterback was a refund.",
  "Yo mamma is so stupid, it took her 2 hours to watch 60 minutes",
  "Yo momma's so stupid, she thought a quarterback was a charity.",
  "Yo mama is so dumb, she cooked her own complimentary breakfast.",
  "Yo momma is so dumb, she makes up more words than Donald Trump.",
  "Yo mama is so stupid that she sent me a fax with a stamp on it.",
  "Yo mama so dumb, she thought Twitter was social media for birds.",
  "Yo mama is so stupid that she bought a solar-powered flashlight!",
  "Yo momma is so stupid that she sat on the TV to watch the couch.",
  "Yo mama so dumb, she went to Burger King and asked for a Big Mac.",
  "Yo mama is so stupid that she sold the house to pay the mortgage.",
  "Yo mama is so stupid that she thinks Johnny Cash is a pay toilet!",
  "Yo mama is so stupid that she thinks deadbeat is a type of music.",
  "Yo mama so dumb she tried to make an appointment with Dr. Pepper.",
  "Yo mamma so dumb she bought a sliding glass door with a peephole.",
  "Yo momma so stupid, she tried to mail a letter using food stamps.",
  "Yo momma so stupid she went to Boost Mobile to fill up her nitro.",
  "Yo mama is so stupid that she locked her keys inside a motorcycle.",
  "Yo momma so stupid it took her four hours to watch « 60 Minutes ».",
  "Yo mamma's so stupid, she uses hair spray to clean her pet rabbit!",
  "Yo mama is so stupid, she had a staring contest with a Ford Focus.",
  "Yo mama is so stupid that it takes her an hour to cook minute rice.",
  "Yo momma's so stupid, she thought Chicken Pot Pie was a fraternity!",
  "Yo mama’s so dim, she held a battery up and said, “I got the power!”",
  "Yo mama’s so clueless, she went to the optometrist to get an iPhone.",
  "Yo mama so stupid, she returned a donut because it had a hole in it.",
  "Yo mamma so stupid she tried to put M&amp;M's in alphabetical order.",
  "Yo momma so stupid, she wanted an apple and went to the Apple Store.",
  "Yo mama so dumb, she thought seaweed was something that fish smoked.",
  "Yo mama's so stupid that when she uses Hotmail she wears oven mitts.",
  "Yo mama is so stupid that she tries to insult you with yo mama jokes.",
  "Yo mama is so stupid that she thought meow mix was a record for cats.",
  "Yo mama is so stupid that if she spoke her mind, she'd be speechless.",
  "Yo mama's so dumb that Rebecca Black taught her the days of the week.",
  "Yo mama so dumb, she put lipstick on her forehead to make up her mind.",
  "Yo mama is so stupid, when she took an IQ test, it came back negative.",
  "Yo mama is so stupid that she called the 7-11 to see when they closed.",
  "Yo momma is so stupid she went to the orthodontist to get a Bluetooth.",
  "Yo mama is so stupid she thought seaweed was something that fish smoke",
  "Yo mama is so stupid that she asked you « What is the number for 911 »?",
  "Yo mama is so stupid she came to a stop sign and waited till it said go",
  "Yo mama is so stupid that she thought menopause was a button on the VCR.",
  "Yo mom is so dumb that she thought Dunkin' Donuts was a basketball team.",
  "Yo momma's so dumb, it takes her an hour and a half to make minute rice.",
  "Yo momma's so stupid, she watches « The Three Stooges » and takes notes.",
  "Yo mamma so stupid she was staring at my Ford because it said « Focus ».",
  "Yo mama is so confusing that even Scooby Doo couldn’t solve that mystery.",
  "Yo momma so dumb that when she was locked in a grocery store she starved!",
  "Yo mama is so stupid that she thought Mick Jagger was a breakfast sandwich!",
  "Yo momma so stupid, she tried to talk into an envelope to send a voicemail.",
  "Yo mama is so dumb, she put sugar on the bed because she wanted sweet dreams.",
  "Yo mama's so stupid she put paper on the television and called it paper view.",
  "Yo' mama so stupid, she walked into an antique shop and asked « What's new »?",
  "Yo mama is so stupid when I asked for a Hot Pocket she lit her pants on fire.",
  "Yo momma's so stupid, she makes Homer Simpson look like a Nobel Prize winner.",
  "Yo mama's so stupid, she got locked in the grocery store and starved to death.",
  "Yo mama’s so silly she told the NFL players to bring spoons to the Super Bowl.",
  "Yo mama so confused, when they said it was chilly outside, she grabbed a bowl.",
  "Yo mama so stupid, she went to the dollar store and said « How much is this »?",
  "Yo momma so stupid when she went to Subway, she asked for a ticket to Chicago.",
  "Yo mama's so dim-witted, she couldn't find her way out of a paper bag with GPS.",
  "Yo mama is so stupid that she put on bug spray before going to the flea market.",
  "Yo mama is so stupid that she thought a lawsuit was something you wear to court.",
  "Yo mama’s so silly, she put a watch in a piggybank and said she was saving time.",
  "Yo mama is so stupid, she wanted to cancel a hockey game due to ice on the field.",
  "Yo mama is so stupid that she thinks Christmas Wrap is Snoop Dogg's holiday album.",
  "Yo mama is so stupid that I saw her in the frozen food section with a fishing rod.",
  "Yo mama is so stupid that she thinks a stereotype is the brand on her clock-radio.",
  "Yo mama is so stupid that she wouldn't know up from down if she had three guesses.",
  "Yo momma so stupid she thought that putting a clock in a fridge would freeze time!",
  "Yo mama so silly, I saw her in a tree talking about how she was the branch manager.",
  "Yo mama's so stupid she got hit by a cup, ran to the police and said she got mugged",
  "Yo mama is so dumb, she got fired from the M&M factory for throwing away all the Ws.",
  "Yo momma so stupid, when I told her that she lost her mind, she went looking for it.",
  "Yo mama's so stupid, she told me to meet her at the corner of 'Walk and Don't Walk.'",
  "Yo momma so stupid, when she saw YMCA, she said « Look, they spelled Macy's wrong ».",
  "Yo mama is so stupid that if you gave her a penny for her thoughts, you'd get change.",
  "Yo mama is so stupid, she walked into Walgreens and said « These walls ain't green ».",
  "Yo momma's so dumb, the psychic hotline only charges her half price to read her mind!",
  "Yo mama is so stupid that she picked up the phone and asked « What button do I push »?",
  "Yo mama's so stupid that whenever someone rings the doorbell, she checks the microwave.",
  "Yo Momma's so dumb that when I told her it was chilly outside, she went and got a bowl.",
  "Your momma's so stupid when my car ran out of gas she came over and farted in the tank.",
  "Yo momma's so stupid, I told her it was chilly outside so she went outside with a spoon.",
  "Yo mamma so stupid she put two M&amp;M's in her ear and said she was listening to Eminem.",
  "Yo mama is so stupid that when asked for her emergency contact number she said « 9-1-1 ».",
  "Yo momma so stupid, when they said, 'Order in the court,' she asked for fries and a shake.",
  "Yo mama's so dense, she thinks 'Limited Edition' means they are giving away free editions.",
  "Yo mama is so stupid that when she went to take the 44 bus, she took the 22 twice instead.",
  "Your mom is so stupid I told her spring was around the corner and she went looking for it.",
  "Yo mama is so stupid that when she heard 90% of all crimes occur around the home, she moved.",
  "Yo momma is so stupid, she put a quarter in a parking meter and said « Where's my gumball »?",
  "Yo mama is so stupid that on her job application where it says emergency contact she put 911.",
  "Yo mama is so stupid that at bottom of application where it says Sign Here - she put Scorpio.",
  "Yo momma is so dumb when someone asked her what the capital of Canada was she answered « C ».",
  "Yo mama is so dumb, where it said « Do not write here » on her application, she wrote « Ok ».",
  "Yo mama is so stupid she took the puzzle back to the store because she thought it was broken!",
  "Yo mama is so stupid when the judge said « Order! Order »! she said « Fries and coke please ».",
  "Yo momma's so stupid, she ordered a cheeseburger from McDonald's and said « Hold the cheese ».",
  "Yo mama is so stupid that when they said they were playing craps she went and got toilet paper.",
  "Yo mama is so stupid she came over to my house and shouted in my mailbox to leave me voicemail.",
  "Yo mama's so stupid that when she broke her VCR, she bought a video tape on how to fix your VCR.",
  "Yo momma's so stupid, she put two quarters in her ears and thought she was listening to 50 Cent.",
  "Yo mamma is so stupid she put 50 cent coins in each ear and thought she was listening to 50 cent",
  "Yo momma is so stupid when your dad sad it was chilly outside, she ran out the door with a spoon!",
  "Yo momma's so stupid, she asked me what jeans I wear. I said « Guess » and she said « Wrangler »?",
  "Yo mama is so stupid that she can't make Jello because she can't fit 2 quarts of water in the box.",
  "Yo mama’s so clueless, when the judge said, “Order in the court,” she asked for fries and a shake.",
  "Yo mama is so fat and dumb she signed up for an email account because she heard it contained spam.",
  "Yo mamma so stupid her password needed 8 characters, so she typed « Snow White and the 7 dwarfs ».",
  "Yo momma is so stupid when I told her Christmas is right around the corner she went looking for it.",
  "Yo momma so stupid, when the dentist said she needed a crown she thought she was going to be queen.",
  "Yo mama is so stupid that she put two M&amp;M's in her ears and thought she was listening to Eminem.",
  "Yo momma is so dumb she put the air conditioning in backwards saying she was going to chill outside.",
  "Yo mama is so stupid that I told her Christmas was just around the corner and she went looking for it.",
  "Yo mama is so stupid that when she saw a « Wrong Way » sign in her rearview mirror, she turned around.",
  "Yo momma's so stupid, that when I saw her shouting in my mailbox, she said she leaving me a voicemail.",
  "Yo mamma is so stupid that she bought some doughnuts and returned them because they had holes in them.",
  "Yo mamma is so stupid, she stopped her car at a stop sign and she's still waiting for it to turn green.",
  "Yo momma's so stupid, when I asked her to purchase me a color television, she asked me « Which color »?",
  "Yo mama is so stupid that she ran outside with a purse because she heard there was change in the weather.",
  "Yo mama is so stupid that when her husband lost his marbles she ran to the store and bought him new ones.",
  "Yo mamma so stupid that when you you were born and she saw your cord, she said « Oh, it comes with cable »!",
  "Yo mama is so stupid that she said « What's that letter after x » and I said Y she said « Cause I wanna know ».",
  "Yo mama is so stupid that when she asked me what kinda jeans I wore, I said Guess and she said « Ummm... Levis »?",
  "Yo momma's so stupid, she tried to hug her reflection in the pool thinking it was her long lost twin, and drowned.",
  "Yo mama is so stupid that when I asked her if she wanted to play one on one, she said « Ok, but what's the teams »?",
  "Yo mama is so stupid that when the judge said « Order in the court »! she said « I'll have a hamburger and a Coke ».",
  "Yo mama's so stupid she was yelling through a letter box, we asked her what she was doing, she said leaving a voicemail",
  "Yo momma's so dumb, when y'all were driving to Disneyland, she saw a sign that said « Disneyland left », so she went home.",
  "Yo mama so stupid she was yelling in her mailbox and when I asked her what she was doing, she said « Sending a voicemail ».",
  "Yo mama's so stupid when she heard of Facebook she went to a book store and asked the book keeper were can I find face book",
  "Yo momma's so dumb, when your aunt had twins, she asked yo momma to name them. She named one Denise, and the other Denephew.",
  "Yo mama is so stupid that when she took you to the airport and a sign said « Airport Left », she turned around and went home.",
  "Yo momma so stupid, when thieves broke into her house and stole the TV, she chased after them shouting, 'Wait, you forgot the remote!'",
  "Yo momma so stupid when she went to go see a movie, it said « under 17 not allowed », so she left to get 16 more friends to go with her.",
  "Yo mama is so stupid that when she worked at McDonald's and someone ordered small fries, she said « Hey Boss, all the small one's are gone ».",
  "Yo mama is so stupid that when I asked her about X-Men she said « Sure, there's Bobby my first baby daddy, Roger the guy I see on Thursdays.. ».",
  "Yo mama is so stupid that I saw her walking down the street yelling into an envelope, asked what she was doing, and she said sending a voice mail.",
  "Yo momma is so stupid when an intruder broke into her house, she ran downstairs, dialed 9-1-1 on the microwave, and couldn't find the « CALL » button.",
  "Yo momma is so stupid, when she went to the movie theater &amp; the movie she wanted to see said « under 17 not allowed », she left &amp; brought back 16 of her friends.",
  "Yo mama so dumb, she got hit by a parked car.",
  "Yo momma so stupid she tried to drown a fish.",
  "Yo momma's so stupid she sold her car for gas money!",
  "Yo mama's so stupid that she bought tickets to Xbox Live.",
  "Yo mama’s so clueless, she brought a spoon to the Super Bowl.",
  "Yo mama's so stupid that she went to the dentist to get a bluetooth.",
  "Your momma is so stupid she asked « What is the number for 911 »?",
  "Yo mama so stupid, she went to the eye doctor to get an iPhone.",
  "Yo mama's so stupid, it takes her two hours to watch 60 Minutes.",
  "Yo momma is so stupid she took a ruler to bed to see how long she slept.",
  "Yo mama so silly, she thought Dunkin’ Donuts was a basketball team.",
  "Your momma is so stupid she put airbags on her computer in case it crashed.",
  "Yo mama is so stupid she asked for a price check at the Dollar Store.",
  "Yo mama's so stupid, when I said, 'Drinks on the house,' she got a ladder.",
  "Yo mama is so clueless, she climbed over a glass wall to see what was on the other side.",
  "Yo momma so dumb, she tried to eat a power mac because she thought it was better than a big mac.",
  "Yo mamma so stupid, she put a quarter in the parking meter and waited for a gumball to come out.",
  "Yo momma is so stupid that when thieves broke in and stole the tv, she ran outside and yelled to them « Hey, you forgot the remote ! »",
  "Yo mama's so dumb, she thought a quarterback was a tax return.",
  "Yo mama's so dumb, she thought the moon was made of cheese... and tried to eat it.",
  "Yo mama's so dumb, she thinks Bluetooth needs mouthwash.",
  "Your mom is so oblivious, she put lipstick on her forehead because she wanted to make up her mind.",
  "Your mother is so intellectually gentle, she blew on her ice cream to cool it down.",
  "Your mother is so dumb she stared at a cup of instant noodles for an hour because the instructions said 'stand for three minutes'.",
  "Ya mama so dumb, she thought a quarterback was change she got at a drive-thru.",
  "Your mom is so dense, she thought a hard drive was just a stressful road trip through the mountains.",
];
