export default [
  "Yo mama so lazy she has a remote for the TV remote.",
  "Yo mama's lazy, she makes couch potatoes look energetic.",
  "Yo mama's unproductive, she makes sloths look like workaholics.",
  "Yo mama's idle, she makes statues look like they have a busy schedule.",
  "Yo mama so lazy, she’s got a remote control just to operate her remote.",
  "Yo mama so lazy that she came in last place in a recent snail marathon.",
  "Yo momma's so slow when she crossed the street she got a parking ticket.",
  "Yo mama's slow, she makes molasses in January seem like it's in a hurry.",
  "Yo mama's inefficient, she couldn't run a microwave, let alone a marathon.",
  "Yo mama's lethargic, she makes snails look like they are competing in NASCAR.",
  "Yo mama's sluggish, she makes turtles look like they are training for the Olympics.",
  "Yo mama's so lazy, she can't even be bothered to finish this joke.",
  "Yo mama's so lazy, she sets her alarm just to ignore it.",
  "Yo mama's so lazy, her spirit animal is a parked car.",
  "Yo mama's so lazy, she takes a siesta during her coffee breaks.",

  "Yo mama's so lazy, she's training to be a professional binge-watcher",
  "Yo mama's so lazy, she outsourced her blinking",
  "Yo mama's so lazy, she hired a personal trainer to teach her how to nap more efficiently",
  "Yo mama's so lazy she's trying to get a cat to do her laundry for her, but it keeps just sitting on the pile and judging her instead",
  "Yo mama so lazy, she started using a drone to deliver her TV remote from the coffee table to the couch, but then she canceled the order because she didn't want to sign for the package.",
  "Yo mama so lazy, she straps her Apple Watch to the Roomba just to close her daily rings.",
  "Yo mama so lazy, she put a \"No Fly Zone\" sticker on her window so she wouldn't have to swat the flies.",  "Your mother is so lazy, she keeps a laser pointer on her nightstand just to trick the cat into flipping the light switch.",
  "Yer ma's so lazy, she puts a pot of water on the stove and waits for global warming to bring it to a boil.",
  "Ya mama so lazy, she ordered DoorDash to deliver her UberEats order from the porch to the couch.",
  "Ya mama so lazy she trained her dog to use a laser pointer just to click 'Next Episode' on Netflix.",
  "Yer ma's so lazy, she ordered delivery from a food truck parked in her own driveway.",
  "Yo momma so lazy, she bought a second Alexa just to tell the first Alexa to turn off the bedroom lights.",
  "Yo mama's so lazy, she ordered DoorDash to her table while sitting inside the restaurant.",
  "Ya mama so lazy, she called in sick to her work-from-home job because she couldn't face the commute from the bed to the couch.",
  "Yo momma so lazy, she doesn't look both ways before crossing the street, she just waits for continental drift to move her to the other side.",
];
