export default [
  "Yo mama’s so loud, she speaks in surround sound.",
  "Yo mama's loud, she could wake up the entire planet with a yawn.",
  "Yo mama's noisy, she could shatter eardrums with a polite cough.",
  "Yo mama's loud, she narrates her own life in public.",
  "Yo mama's so loud, her yawn sounds like a rock concert.",
  "Yo mama's so loud, even soundproof walls need earplugs.",
  "Yo mama's so loud, her whispers start avalanches.",

  "Yo mama’s so loud, she accidentally started a mosh pit at a library book sale",
  "Yo mama’s so loud, her karaoke night caused a nearby seismograph to register a minor earthquake",
  "Yo mamma's so loud, even her silent films come with subtitles!",
  "Yo mama's so loud, they named a freight train after her",
  "Your mom is so loud, when she laughs, local wildlife starts fleeing the area.",  "Yo momma so loud, when she sighs, the local wind turbine farm generates enough clean energy to power a small European nation.",
  "Yo mama so loud, when she sighs, wind turbines in three neighboring states set new generation records.",
  "Your mother is so loud, she disproved the vacuum of space; NASA heard her clear her throat from Mars.",
  "Yer ma's so loud, when she whispers a secret in New York, the NSA registers a noise complaint in a secure bunker in Utah.",
  "Yo mama's so loud, when she yawns, local bats suffer from severe echolocation interference and crash into parked cars.",
  "Ya mama so loud, when she whispers a secret, Shazam identifies it as a heavy metal concert.",
];
