export default [
  "Yo mama's so weird, she names her shoes.",
  "Yo mama's so weird, she irons her socks.",
  "Yo momma so crusty Pizza Hut is jealous.",
  "If pigs could fly, your mom would have wings.",
  "Yo mama's crude, she makes truck drivers blush.",
  "Yo mama so broke she can't even afford to lose.",
  "Yo mama's cruel, she laughs when kittens sneeze.",
  "Yo mama so strict, she locked you up in a tower.",
  "Yo mama's unpleasant, even silence is preferable.",
  "Yo mama's slow, she still uses Internet Explorer.",
  "Yo momma's so strong, she can drink peanut butter!",
  "Yo mama so American, she deep-fries her toothpaste.",
  "Yo mama's so weird, she talks to herself on FaceTime.",
  "Yo mama's incompetent, she couldn't manage a pet rock.",
  "Yo mama so ridiculous, she tried to climb Mountain Dew.",
  "Yo mama's disruptive, she could ruin a mime convention.",
  "Yo momma is so paranoid, they call her the alarm belle.",
  "Yo momma like a prize fish: I can mount her or eat her.",
  "Yo mama so unfunny, she ruins every joke she ever tells.",
  "Yo mama's awkward, she makes robots seem smooth dancers.",
  "Yo mama's so broke that she couldn't even pay attention.",
  "Yo mama is just like a lawn mower: everyone gets a push.",
  "Yo mama's unkind, she makes tax collectors seem generous.",
  "Yo mama's inept, she couldn't organize a two-car funeral.",
  "Yo mama's sensitive, she brings tissues to action movies.",
  "Yo mama teeth so yellow, I can’t believe it’s not butter.",
  "Yo mama glasses are so thick she can see into the future.",
  "Yo mama is so dark that she got her tattoo done in chalk!",
  "Yo mama's forehead is so big, you could show slides on it.",
  "Yo mama’s so cold, she gives everyone around her frostbite.",
  "Yo mama’s such a mess, Fix-It Felix said, “I can’t fix it.”",
  "Yo mama's offensive, she makes reality TV seem educational.",
  "Yo mama's vulgar, she makes stand-up comedians seem subtle.",
  "Yo mama's graceless, she makes hippos look like ballerinas.",
  "Yo momma is so ashy, every time she rubs her arms it snows.",
  "Yo momma's so broke, she got an eviction notice on her car.",
  "Yo mama's annoying, she sets off car alarms by walking past.",
  "Yo momma's like the Pillsbury Doughboy, everybody pokes her.",
  "Yo mama so American, her birthday song is the National Anthem.",
  "Yo mama so ridiculous, she thought a quarterback was a refund.",
  "Yo mama's bothersome, she makes telemarketers sound appealing.",
  "Yo mama so strict, she grounded you for getting a silver medal.",
  "Yo mama's irritating, she could make a cactus lose its needles.",
  "Yo mama's meddling, she could backseat drive a self-driving car.",
  "Yo mama's obnoxious, she could make a rock star want to whisper.",
  "Yo mama's sensitive, she cries when the toaster burns her toast.",
  "Your mom has been bounced on more times than the « i » in Pixar.",
  "Yo mama such a bad cook, the foods throw itself into the garbage.",
  "Yo mama so American, she sued McDonald’s for selling French fries.",
  "Yo mama’s so stern, they don’t give her Happy Meals at McDonald’s.",
  "Yo mama’s sense of humor is so dry, her best jokes are your worst.",
  "Yo mama's exasperating, she could drive a saint to become a sinner.",
  "Your mom is like a hockey player: she only showers after 3 periods.",
  "Yo mama's irrelevant, history classes fast-forward through her life.",
  "Yo mama so strict, she wants you home before, during, and after dark.",
  "Yo mama so strict, she enforced a curfew for the entire neighborhood.",
  "Yo mama is like a campfire: everybody gets to stick their wieners in.",
  "Yo mama’s cooking is so bad, every April Fool’s she cooks a good meal.",
  "Yo mama's nosy, she could find your secrets even if you don't have any.",
  "Yo mama's unimportant, she's not even a footnote in the history of lint.",
  "Yo mama's scatterbrained, she forgets what she's mad about mid-argument.",
  "Yo mama's interfering, she could edit your dreams while you're sleeping.",
  "Yo mama's slow, she makes molasses in January seem like it's in a hurry.",
  "Yo mama's insignificant, she makes dust motes feel like celestial bodies.",
  "Yo mama's boring, she makes watching paint dry seem like an action movie.",
  "Yo mama's intrusive, she could make solitude feel like a crowded elevator.",
  "Yo mama's aggravating, she could test the patience of a saint on vacation.",
  "Yo mama so dark when I clicked on her profile pic, I thought my phone died.",
  "Yo mama's tasteless, she makes airplane food look like a Michelin star meal.",
  "Your mama's like a race car driver because she burns through a lot of rubber.",
  "Yo mama’s bag is so cluttered it’s like the inside of a dollar store in there.",
  "Yo mama’s teeth are so yellow that when she smiled at traffic, it slowed down.",
  "Yo mama's absentminded, she'd forget her own birthday if it wasn't on Facebook.",
  "Yo mama moves so slow that when she walked past the TV, I missed three episodes.",
  "Yo mama's forgetful, she makes short-term memory look like a lifetime commitment.",
  "Yo mama's useless, she couldn't find her car keys if they were glued to her hand.",
  "Yo mama’s so protective, she covered you in Band-Aids before you got the boo-boos.",
  "Yo mama so bad at directions, when she saw the “Disneyland left” sign, she went home.",
  "Yo mama glasses are so thick that when she looks on a map, she can see people waving.",
  "Yo mama is so dark that she was riding a motorcycle and got a ticket for tinted windows!",
  "Yo mama’s such a bad cook, the flies got together and fixed the hole in the window screen.",
  "Yo momma's so bucked toothed, when she bowed her head to pray, she bit a hole in her chest.",
  "Yo momma is such a ho they call her house Kum &amp; Go because all the men « Kum &amp; Go ».",
  "Your momma's credit is so bad, the bank won't even lend her a pen to fill out a credit application.",
  "Yo mama’s so bad with directions, she saw a “Disneyland left” sign on the way to the theme park, so she went home.",
  "Yo mama so unpopular, her spam folder is empty because even the scammers got tired of her texting them back.",
  "Your mom is so literal, she put a clock in her purse because she wanted to spend some time.",
];
