export default [
  "Yo mama's so scary, she has to trick-or-treat by phone.",
  "Yo mama so scary, her birthday got moved Halloween.",
  "Yo mama so scary, the robber ran away once he saw her.",
  "Yo mama is so scary, she made dirt look like a supermodel.",
  "Yo mama so scary, she made One Direction go the other direction.",
  "Yo mama so scary, she threw a boomerang, and it refused to come back.",
  "Yo mama so scary, you thought the monsters in your closet were friends.",
  "Yo mama’s so scary that when she went to the zoo, the lions and tigers hid from her.",
  "Yo mama's so scary, even Freddy Krueger sleeps with the lights on.",
  "Yo mama's so scary, jack-o’-lanterns scream back.",

  "Yo mama’s so scary, haunted houses charge *her* for the experience",
  "Your mom is so scary, she makes zombies reapply for health insurance",  "Your mom is so terrifying, Bloody Mary looked in the mirror and whispered her name three times just to escape.",
  "Ya mama so creepy, her sleep paralysis demon wakes up in a cold sweat dreaming about her.",
  "Yo momma so scary, when she got possessed, the demon had to call an exorcist to get her out of him.",
  "Yo mama's so spooky, her own shadow refuses to follow her unless it's allowed to hold a flashlight.",
  "Yo mama so scary, the Grim Reaper leaves his scythe on the porch and calls her 'Ma'am'.",
  "Yo momma so creepy, when she watched 'The Ring', Samara crawled back into the TV and locked the well from the inside.",
];
