export default [
  "Yo mama so skinny she can dodge raindrops.",
  "Yo momma so skinny she hang glides with Doritos.",
  "Yo momma so skinny her eyes are in a single file.",
  "Yo mama is so skinny that she can dodge rain drops.",
  "Yo mama so scrawny she makes skinny jeans look fat.",
  "Yo mama is so skinny, she hula hoops with a Cheerio.",
  "Yo momma so skinny she can hula hoop with a Cheerio.",
  "Yo mama is so skinny that she looks like a mic stand.",
  "Yo momma is so skinny she uses a Cheerio as a hula hoop.",
  "Yo mamma so skinny, she uses dental floss as toilet paper.",
  "Yo mama is so skinny that she uses Chapstick for deodorant.",
  "Yo Mama So Skinny She Could Only Fit One Stripe On Her PJs.",
  "Yo mama is so skinny that she uses a Band-Aid as a maxi-pad.",
  "Yo mama is so skinny that her pants only have one belt loop.",
  "Yo mama is so skinny that she turned sideways and disappeared.",
  "Yo mama is so skinny that she only has one stripe on her pajamas.",
  "Yo mama is so dirty that when she takes a bath she becomes skinny.",
  "Yo mama is so skinny that I could blind-fold her with dental floss.",
  "Yo mama is so skinny that she goes hot tubbing with the Mini Wheats Man.",
  "Yo mama is so skinny that her bra fits better when she wears it backwards.",
  "Yo mama is so skinny that she had to stand in the same place twice to cast a shadow.",
  "Yo mama is so skinny that you can save her from drowning by tossing her a Fruit Loop.",
  "Yo mama is so skinny that instead of calling her your parent, you call her transparent.",
  "Yo mama is so skinny that if she had a sesame seed on her head, she'd look like a push pin.",
  "Yo mama is so skinny that if she had a yeast infection she'd be a Quarter Pounder with Cheese.",
  "Yo mama is so skinny that when she swallowed a meatball, everyone thought she was pregnant again.",
  "Yo mama is so skinny that if she had dreads I'd grab her by the ankles and use her to mop the floor.",
  "Yo mama is so skinny that if she turned sideways and stuck out her tongue, she would look like a zipper.",
  "Yo mama is so skinny that when she takes a bath and lets the water out, her toes get caught in the drain.",
  "Yo mama's so skinny, she can see out the peephole with both eyes.",
  "Yo mama is so skinny that she has to run around in the shower to get wet.",
  "Yo mama's so skinny, she can hide behind a toothpick.",
  "Yo mama's so skinny, her hug is just a breeze.",

  "Yo mama's so skinny, when she steps on a bathroom scale it's like someone forgot to put batteries in it",
  "Yo mama so skinny, she used a Cheeto as a yoga bolster and the structural integrity of the snack remained completely uncompromised.",  "Ya mama so skinny, she has to wear her Apple Watch as a belt.",
  "Yo mama's so skinny, she uses a single strand of spaghetti as a pool noodle.",
  "Yo mama so skinny she can hula hoop with a Cheerio.",
];
