export default [
  "Yo mama's so tall, she can see her house from anywhere.",
  "Yo mama's so tall, she uses two 100-foot ladders as crutches.",
  "Yo momma's so fat, when she sits down, she's three feet taller.",
  "Yo mama's so tall, she did a push-up and burned her back on the sun.",
  "Yo mama so tall, she tripped in Michigan and hit her head in Florida.",
  "Yo mama's so tall, she makes Shaquille O'Neal look like Gary Coleman.",
  "Yo mama so tall, she tripped over a rock and hit her head on the moon.",
  "Yo mama is so tall, when she jumped up and did a backflip she kicked Jesus",
  "Yo mamma is so tall when she did a back flip, she kicked Jesus in the face.",
  "Yo mama is so tall that if she did a back-flip she'd kick Jesus in the mouth.",
  "Yo mama's so tall, she has to take out the driver's seat of her car and sit in the back to operate the vehicle.",
  "Yo mama's so tall, she can play basketball with clouds.",
  "Yo mama's so tall, her hugs come with altitude sickness.",

  "Yo mama's so tall, she has to ask the Empire State Building for directions",
  "Yo mama's so tall, she gets her Wi-Fi from satellites",
  "Yo mama's so tall, she has to file a 1099 form for every sunset she blocks",
  "Yo mama's so tall, she needs a weather report before she bends over to pick up a penny",
  "Yo mama's so tall, she gets her shoe size in area codes",
  "Yo mama's so tall, she has to ask the giraffe for a reach-up",  "NASA actually had to adjust the trajectory of the International Space Station because your mother stood up to stretch and accidentally photobombed a deep-space transmission.",
  "Yer ma's so tall, she can stand in the deepest part of the Mariana Trench and still get a sunburn from the Aurora Borealis.",
  "Your mom is so tall, King Kong climbed up her leg to get a better view of the city.",
  "Ya mama so tall, she stepped on a Lego in 1998 and the pain signal is still traveling up her nervous system to reach her brain.",
  "Your mother is so tall, she didn't need a parachute to go skydiving; she just stepped out of the plane and waited for her feet to touch the ground.",
  "Yer ma's so tall, she went for a swim in the ocean and caused a tsunami warning on three different continents.",
  "Yo mama's so tall, when she tripped over a curb she didn't fall down, she just entered a stable low Earth orbit.",
  "Your mother is so tall, she could stand in the Mariana Trench and still get a sunburn on her shoulders.",
  "Your mother is so tall, she stood up to stretch and accidentally photobombed the James Webb Space Telescope.",
];
